name: Create Release

on:
  push:
    branches: [ "master" ]
#    tags:
#      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Set release filename
        run: |
          VERSION=${GITHUB_REF_NAME}
          FILENAME="${{ env.PROJECT_NAME }}${VERSION}.zip"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Archive published output
        run: zip -r "$FILENAME" publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
